### ISSUE TITLE
Error in if (ns > 0) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by afm1989** [Jfortin1/neuroCombat_Rpackage#1]
getting this error when trying to run combat in R...I have a data matrix, a batch specifying different sites, and a matrix with biological variables. I've removed all rows that have all NAs. What's causing this?

**Comment by Jfortin1** [comment]
Could you add the results of 
```
ns <- rowSums(is.na(dat))
print(ns)
```
here?

**Comment by afm1989** [comment]
Sure, it was too many entries so I saved it to a dataframe called "test"
and when I view that, it looks like this (column V1 has 5s all the way
down):

[image: Screen Shot 2021-06-08 at 7.31.56 PM.png]

**Comment by Jfortin1** [comment]
Could you show the output of the following:
```
ns <- rowSums(is.na(dat))
print(sum(ns==ncol(data)))
```

**Comment by afm1989** [comment]
Output is:

[1] 145

**Comment by afm1989** [comment]
Hi,

Just wanted to follow up on this - any idea what's causing the error?

Thanks!!
Alex

**Comment by AlexHatoum** [comment]
Hello, 

I am having the same issue, and I have no missing data in my file. 

A.S.H.

**Comment by Jfortin1** [comment]
@AlexHatoum What is the output of

 ```
ns <- rowSums(!is.finite(dat))
print(sum(ns==ncol(dat)))
```

**Comment by afm1989** [comment]
It turned out that for me this was an error with the version of R I was using. I forget exactly which line ran into the error, but when I used an older version of R it ran correctly. I’ll see if I can find and post some more information about where the error originates.
