### ISSUE TITLE
Unable to install neurocombat on mac (R version 4.3.2)

### ISSUE THREAD

**Issue by emilyharriott** [Jfortin1/neuroCombat_Rpackage#6]
Dear all,

I am so excited to start using this package with my data! But unfortunately am struggling to download the package into my R studio environment. I am hoping someone on here might be able to help.

I followed the instructions and did these things exactly:

install.packages("devtools") # if you have not installed "devtools" package
library(devtools)
install_github("jfortin1/neuroCombatData")
install_github("jfortin1/neuroCombat_Rpackage")

And got this error:
Show in New Window
Error: Failed to install 'neuroCombatData' from GitHub:
  Command failed (1)

The whole traceback looks like this: 
![Screenshot 2024-02-26 at 12 10 34 PM](https://github.com/Jfortin1/neuroCombat_Rpackage/assets/110205277/aedf70c5-af20-4be9-9a5c-8649370797b9)

How can I download this package? Or is this the wrong package to download and I should be downloading and using another package or another version? Any assistance you might be able to provide would be so greatly appreciated.

Thank you so much!
Emily

**Comment by Jfortin1** [comment]
The other way around:

```
devtools::install_github("Jfortin1/neuroCombat_Rpackage")
devtools::install_github("Jfortin1/neuroCombatData")
```
